# Generated by Django 3.2.9 on 2022-08-02 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('fr', 'fruits'), ('ve', 'vegetables'), ('me', 'meat'), ('mi', 'milk & derivatives'), ('pa', 'panties'), ('sh', 'shirts'), ('ca', 'caps'), ('hu', 'hours'), ('ho', 'homes'), ('co', 'computers'), ('ph', 'phones')], default='fr', max_length=20)),
                ('price', models.FloatField(default=0.0)),
                ('description', models.TextField(max_length=255)),
                ('piece', models.IntegerField(default=0)),
                ('min_order', models.IntegerField(default=0)),
                ('currency', models.CharField(default='mad', max_length=20)),
                ('unit', models.CharField(default='kg', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='%y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.product')),
            ],
        ),
    ]
