# Generated by Django 3.2.9 on 2022-08-14 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 14, 16, 1, 2, 579542)),
        ),
        migrations.AddField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 14, 16, 1, 2, 579542)),
        ),
    ]
