# Generated by Django 3.2.9 on 2022-08-15 17:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20220814_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 15, 18, 59, 26, 682445)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 15, 18, 59, 26, 682445)),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 8, 15, 18, 59, 26, 682445))),
                ('see', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receive', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
