# Generated by Django 3.2.9 on 2022-08-27 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220815_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='owner',
            new_name='client',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 1, 51, 999929)),
        ),
        migrations.AlterField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 27, 15, 1, 51, 999929)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 27, 15, 1, 51, 999929)),
        ),
    ]
