# Generated by Django 3.2.9 on 2022-08-27 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220827_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='client',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 15, 28, 54, 769513)),
        ),
        migrations.AlterField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 27, 15, 28, 54, 769513)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 8, 27, 15, 28, 54, 769513)),
        ),
    ]
