# Generated by Django 3.2.9 on 2022-09-04 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220827_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 4, 18, 34, 191567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 4, 4, 18, 34, 191567, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 4, 4, 18, 34, 191567, tzinfo=utc)),
        ),
    ]
