# Generated by Django 3.2.9 on 2022-09-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20220904_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='order',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_order',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='piece',
            field=models.FloatField(default=0),
        ),
    ]
